name: hypersearch
dependencies:
     - python==3.6.3
     - pip:
         - bokeh==0.13.0
         - dask-glm==0.1.0
         - dask-jobqueue==0.4.0
         - dask-ml==0.10.0
         - dask==0.19.4
         - distributed==1.23.3
         - matplotlib==2.1.0
         - numpy==1.15.2
         - pandas==0.23.4
         - pytest
         - scikit-learn==0.19.1
         - scikit-optimize==0.5.2
         - scipy==1.0.0
         - tornado-4.5.1
